/**
 * `.ass` export: one Style per speaker so the burned-in captions come out in
 * each speaker's colour, with the Actor field carrying the speaker name.
 */

import type { Cue, Settings, Speaker } from "../types";
import { formatAssTime } from "./time";

const DEFAULT_STYLE = "Default";
const DEFAULT_COLOR = "#ffffff";

/** Margins in PlayRes units. Exported so the preview can place text identically. */
export const ASS_MARGIN_V = 40;
export const ASS_MARGIN_H = 40;

/** ASS colours are `&HAABBGGRR` — byte-reversed from hex, alpha 00 = opaque. */
export function hexToAssColor(hex: string, alpha = 0): string {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  const rgb = m ? m[1] : DEFAULT_COLOR.slice(1);
  const r = rgb.slice(0, 2);
  const g = rgb.slice(2, 4);
  const b = rgb.slice(4, 6);
  const a = alpha.toString(16).padStart(2, "0");
  return `&H${a}${b}${g}${r}`.toUpperCase();
}

/**
 * Style names may not contain commas (the format is comma-delimited) and must be
 * unique, since two speakers can legitimately share a display name.
 */
function styleNames(speakers: Speaker[]): Map<string, string> {
  const used = new Set<string>([DEFAULT_STYLE]);
  const names = new Map<string, string>();

  for (const speaker of speakers) {
    const base =
      speaker.name.replace(/[,\r\n{}]/g, " ").trim().replace(/\s+/g, "_") || "Speaker";
    let name = base;
    let n = 2;
    while (used.has(name)) {
      name = `${base}_${n++}`;
    }
    used.add(name);
    names.set(speaker.id, name);
  }
  return names;
}

/**
 * SRT text carries a little inline HTML. Convert what maps cleanly to ASS
 * override tags and drop the rest.
 */
export function toAssText(text: string): string {
  return (
    text
      // Escape first: a brace in the dialogue itself would open an override
      // block. Doing this before inserting tags leaves the tags below intact,
      // and HTML tags contain no braces so they pass through unchanged.
      .replace(/\{/g, "\\{")
      .replace(/\}/g, "\\}")
      .replace(/<\s*i\s*>/gi, "{\\i1}")
      .replace(/<\s*\/\s*i\s*>/gi, "{\\i0}")
      .replace(/<\s*b\s*>/gi, "{\\b1}")
      .replace(/<\s*\/\s*b\s*>/gi, "{\\b0}")
      .replace(/<\s*u\s*>/gi, "{\\u1}")
      .replace(/<\s*\/\s*u\s*>/gi, "{\\u0}")
      // Drop any remaining markup (font tags, spans) with no ASS equivalent.
      .replace(/<[^>]*>/g, "")
      .replace(/\r?\n/g, "\\N")
      .trim()
  );
}

export interface AssOptions {
  settings: Settings;
  /** Video dimensions, so font sizes are relative to the real frame. */
  width: number;
  height: number;
}

export function buildAss(cues: Cue[], speakers: Speaker[], options: AssOptions): string {
  const { settings } = options;
  const width = options.width > 0 ? options.width : 1920;
  const height = options.height > 0 ? options.height : 1080;
  const names = styleNames(speakers);
  const byId = new Map(speakers.map((s) => [s.id, s]));

  const styleLine = (name: string, color: string) =>
    [
      `Style: ${name}`,
      settings.fontName,
      String(settings.fontSize),
      hexToAssColor(color),
      hexToAssColor(color),
      hexToAssColor(settings.outlineColor),
      // BackColour doubles as the shadow colour, half-transparent as usual.
      hexToAssColor(settings.shadowColor, 0x80),
      settings.bold ? "-1" : "0", // Bold
      "0", // Italic
      "0", // Underline
      "0", // StrikeOut
      "100", // ScaleX
      "100", // ScaleY
      "0", // Spacing
      "0", // Angle
      "1", // BorderStyle: outline + shadow
      String(settings.outline),
      String(settings.shadow),
      "2", // Alignment: bottom centre
      String(ASS_MARGIN_H), // MarginL
      String(ASS_MARGIN_H), // MarginR
      String(ASS_MARGIN_V), // MarginV
      "1", // Encoding
    ].join(",");

  const header = [
    "[Script Info]",
    "; Generated by sub-sub-title",
    "ScriptType: v4.00+",
    "WrapStyle: 0",
    "ScaledBorderAndShadow: yes",
    `PlayResX: ${width}`,
    `PlayResY: ${height}`,
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, " +
      "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, " +
      "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    styleLine(DEFAULT_STYLE, DEFAULT_COLOR),
    ...speakers.map((s) => styleLine(names.get(s.id) ?? DEFAULT_STYLE, s.color)),
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
  ];

  const events = [...cues]
    .sort((a, b) => a.start - b.start)
    .map((cue) => {
      const speaker = cue.speakerId ? byId.get(cue.speakerId) : undefined;
      const style = speaker ? names.get(speaker.id) ?? DEFAULT_STYLE : DEFAULT_STYLE;
      const actor = speaker?.name.replace(/[,\r\n]/g, " ") ?? "";
      return [
        "Dialogue: 0",
        formatAssTime(cue.start),
        formatAssTime(cue.end),
        style,
        actor,
        "0",
        "0",
        "0",
        "",
        toAssText(cue.text),
      ].join(",");
    });

  return [...header, ...events, ""].join("\n");
}
